language: python
cache: pip
matrix:
  include:
  - os: linux
    dist: xenial
    sudo: false
    python: '2.6'
  - os: linux
    dist: xenial
    sudo: false
    python: '2.7'
  - os: linux
    dist: xenial
    sudo: false
    python: '3.2'
  - os: linux
    dist: xenial
    sudo: false
    python: '3.3'
  - os: linux
    dist: xenial
    sudo: false
    python: '3.4'
  - os: linux
    dist: xenial
    sudo: false
    python: '3.5'
  - os: linux
    dist: xenial
    sudo: false
    python: '3.6'
  - os: linux
    dist: xenial
    sudo: false
    python: '3.7-dev'
  - os: linux
    dist: xenial
    sudo: false
    python: 'nightly'
  - os: linux
    dist: xenial
    sudo: false
    python: 'pypy'
  - os: linux
    dist: xenial
    sudo: false
    python: 'pypy3'
  - os: osx
    language: generic
    env: PYENV_VERSION=2.7.12
  - os: osx
    language: generic
    env: PYENV_VERSION=3.5.2
before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    # Per the `pyenv homebrew recommendations <https://github.com/yyuu/pyenv/wiki#suggested-build-environment>`_.
    brew install openssl readline
    # See https://docs.travis-ci.com/user/osx-ci-environment/#A-note-on-upgrading-packages.
    # I didn't do this above because it works and I'm lazy.
    brew outdated pyenv || brew upgrade pyenv
    # virtualenv doesn't work without pyenv knowledge. venv in Python 3.3
    # doesn't provide Pip by default. So, use `pyenv-virtualenv <https://github.com/yyuu/pyenv-virtualenv/blob/master/README.md>`_.
    brew install pyenv-virtualenv
    pyenv install $PYTHON
    # I would expect something like ``pyenv init; pyenv local $PYTHON`` or
    # ``pyenv shell $PYTHON`` would work, but ``pyenv init`` doesn't seem to
    # modify the Bash environment. ??? So, I hand-set the variables instead.
    export PYENV_VERSION=$PYTHON
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
    pyenv-virtualenv venv
    source venv/bin/activate
    # A manual check that the correct version of Python is running.
    python --version
  fi
install:
  - pip install codecov
  - pip install -r requirements.txt
  - pip install -e .
script:
  - PYTHONPATH=.:$PYTHONPATH python tests/__main__.py
after_success:
  - PYTHONPATH=.:$PYTHONPATH coverage run --omit=*test* tests/__main__.py
  - codecov
